### PR TITLE
Using requestor display name instead of name

### PR DESCRIPTION
**Pull request by Logerfo**

### CODE REVIEW

**Comment by Logerfo** [comment]
CI is configured for ruby 🤔

**Comment by bsquidwrd** [comment]
The CI was configured to try to build anything, even without a `.travis.yml` file.

I had to go through each repo manually and turn them off. GitHub is migrating from travis-ci.org to travis-ci.com (even for open source repos)

**Comment by Logerfo** [comment]
@bsquidwrd is your instance running the last commit? I still get the requestor name instead of display name.

**Comment by bsquidwrd** [comment]
Yup, and that's odd. When I run it I see it get the display name 🤔 

I'll do a bit more testing today.

**Comment by Logerfo** [comment]
image

**Comment by bsquidwrd** [comment]
I found the issue. It lies here:

https://github.com/bsquidwrd/Quote-Bot/blob/ab344500bf8abc31deb3ab44b761eecbdace2276/cogs/quote.py#L57

**Comment by bsquidwrd** [comment]
Yup, made a change and it solved it 😄 
https://github.com/bsquidwrd/Quote-Bot/blob/48bcc9cec7d998be707f50c972b7f65ba0ccd0bc/cogs/quote.py#L57

**Pull request merged**
